#!/usr/bin/env bash
# Sets up the WireGuard server that sits behind the obfuscator, and issues
# client bundles for it.
#
# This exists because the two steps easiest to get wrong by hand are also
# the two that matter most:
#
#   * WireGuard must listen on loopback only. If its port is reachable
#     from the internet, a censor sees unobfuscated WireGuard directly and
#     everything the obfuscator does is pointless — while the tunnel still
#     appears to work, so nothing tells you.
#
#   * The interface MTU must leave room for the obfuscator's 42 bytes.
#     WireGuard's default of 1420 does not, and the result is silent
#     fragmentation: slower, and a traffic pattern of its own.
#
# Usage:
#   sudo ./deploy/provision-wireguard.sh init [--dry-run]
#   sudo ./deploy/provision-wireguard.sh add-client <name> <server-host> [--dry-run]
#   sudo ./deploy/provision-wireguard.sh verify
#
# --dry-run prints what would be written and changes nothing.
set -euo pipefail

WG_INTERFACE="${WG_INTERFACE:-wg0}"
WG_PORT="${WG_PORT:-51821}"          # loopback only; the obfuscator forwards here
WG_SUBNET="${WG_SUBNET:-10.55.0}"    # /24 for the tunnel
WG_MTU=1376                          # see deploy note above and README
WG_DIR="/etc/wireguard"
WG_CONF="${WG_DIR}/${WG_INTERFACE}.conf"
CLIENTS_FILE="${CLIENTS_FILE:-/etc/obfsvpn/clients.yaml}"
OBFSCTL="${OBFSCTL:-obfsctl}"

DRY_RUN=false

log()  { echo "==> $*"; }
warn() { echo "WARNING: $*" >&2; }
die()  { echo "error: $*" >&2; exit 1; }

require_root() {
	if ! $DRY_RUN && [[ "$(id -u)" -ne 0 ]]; then
		die "run as root, or pass --dry-run to see what would happen"
	fi
}

# emit writes content to a path, or prints it under --dry-run.
emit() {
	local path="$1" mode="$2" content="$3"
	if $DRY_RUN; then
		echo "--- would write ${path} (mode ${mode}) ---"
		echo "$content"
		echo "--- end ${path} ---"
		return
	fi
	install -m "$mode" /dev/null "$path"
	printf '%s\n' "$content" > "$path"
}

# default_route_interface finds the NIC that reaches the internet, which is
# what traffic leaving the tunnel has to be masqueraded onto.
default_route_interface() {
	ip route show default 2>/dev/null | awk '/default/ {print $5; exit}'
}

server_config() {
	local private_key="$1" wan="$2"
	cat <<EOF
# Generated by provision-wireguard.sh
#
# ListenPort is bound to loopback by the PreUp rule below: the only thing
# that should be reachable from the internet is the obfuscator. If you
# ever see this port open from outside, the obfuscation is not protecting
# anything.
[Interface]
Address = ${WG_SUBNET}.1/24
ListenPort = ${WG_PORT}
PrivateKey = ${private_key}

# Leaves room for the obfuscator's 42 bytes of wrapping inside a
# 1500-byte path. Raising this reintroduces fragmentation.
MTU = ${WG_MTU}

# Refuse anything arriving at the WireGuard port from outside the host.
# The obfuscator connects over loopback; a packet from anywhere else means
# either a misconfiguration or somebody probing directly.
PreUp = iptables -I INPUT -p udp --dport ${WG_PORT} ! -s 127.0.0.1 -j DROP
PostDown = iptables -D INPUT -p udp --dport ${WG_PORT} ! -s 127.0.0.1 -j DROP

# Give tunnelled clients a route out.
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ${wan} -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ${wan} -j MASQUERADE
EOF
}

# route_exclusion writes the hooks that keep the obfuscator's own
# connection to the server out of the tunnel.
#
# With AllowedIPs 0.0.0.0/0, wg-quick installs a rule sending every
# unmarked packet into the tunnel. WireGuard's own encrypted packets
# escape it because WireGuard marks its socket; the obfuscator is a
# separate process whose socket carries no mark, so its packets to the
# server would be routed into the tunnel it is itself carrying. The
# tunnel then never comes up, and the symptom says nothing about the
# cause.
#
# A host route fixes it: the rule that consults the main table suppresses
# only default routes, so a /32 there is honoured and the packet leaves
# by the physical interface.
route_exclusion() {
	local server_ip="$1"
	if [[ -z "$server_ip" ]]; then
		cat <<'EOF'

# WARNING: no server IP was available when this was generated, so the
# route that keeps the obfuscator's traffic out of the tunnel is missing.
# Without it the tunnel will not come up. Add it, replacing SERVER_IP:
#
#   PostUp = ip route add SERVER_IP via $(ip route show default | awk '{print $3; exit}') || true
#   PostDown = ip route del SERVER_IP || true
EOF
		return
	fi
	cat <<EOF

# Keeps the obfuscator's own connection to the server outside the tunnel.
# Without this the tunnel would carry the traffic that is carrying it.
PostUp = ip route add ${server_ip}/32 via \$(ip route show default | awk '{print \$3; exit}') || true
PostDown = ip route del ${server_ip}/32 || true
EOF
}

client_wireguard_config() {
	local client_private="$1" server_public="$2" address="$3" server_host="${4:-}"
	local server_ip=""
	if [[ -n "$server_host" ]]; then
		server_ip="$(getent ahostsv4 "$server_host" 2>/dev/null | awk '{print $1; exit}')"
		[[ -n "$server_ip" ]] || server_ip="$server_host"
	fi

	cat <<EOF
[Interface]
PrivateKey = ${client_private}
Address = ${address}/32
DNS = 1.1.1.1

# Must match the server: the obfuscator adds 42 bytes to every packet.
MTU = ${WG_MTU}

$(route_exclusion "$server_ip")

[Peer]
PublicKey = ${server_public}
AllowedIPs = 0.0.0.0/0, ::/0

# Not the server's address. WireGuard talks to the local obfuscator, which
# is what carries the traffic onward.
Endpoint = 127.0.0.1:${WG_PORT}
PersistentKeepalive = 25
EOF
}

cmd_init() {
	require_root
	# Only a real run needs the tools: --dry-run exists so an operator can
	# read the configuration before installing anything.
	if ! $DRY_RUN; then
		command -v wg >/dev/null || die "wireguard-tools is not installed (apt install wireguard-tools)"
	fi

	if ! $DRY_RUN && [[ -f "$WG_CONF" ]]; then
		die "${WG_CONF} already exists; refusing to overwrite an existing server"
	fi

	local wan
	wan="$(default_route_interface || true)"
	if [[ -z "$wan" ]]; then
		$DRY_RUN || warn "could not detect the internet-facing interface; using eth0"
		wan="eth0"
	fi

	local private_key public_key
	if $DRY_RUN; then
		private_key="<generated>"
		public_key="<derived>"
	else
		mkdir -p "$WG_DIR"
		chmod 700 "$WG_DIR"
		private_key="$(wg genkey)"
		public_key="$(printf '%s' "$private_key" | wg pubkey)"
		printf '%s\n' "$public_key" > "${WG_DIR}/server.pub"
		chmod 644 "${WG_DIR}/server.pub"
	fi

	emit "$WG_CONF" 600 "$(server_config "$private_key" "$wan")"

	if $DRY_RUN; then
		echo "--- would enable IPv4 forwarding and start wg-quick@${WG_INTERFACE} ---"
		return
	fi

	log "enabling IPv4 forwarding"
	printf 'net.ipv4.ip_forward = 1\n' > /etc/sysctl.d/99-obfsvpn.conf
	sysctl -q -p /etc/sysctl.d/99-obfsvpn.conf

	log "starting wg-quick@${WG_INTERFACE}"
	systemctl enable --now "wg-quick@${WG_INTERFACE}"

	cat <<EOF

WireGuard is up on 127.0.0.1:${WG_PORT}, MTU ${WG_MTU}.

Next:
  1. Point the obfuscator at it: local_addr: "127.0.0.1:${WG_PORT}"
  2. Open ONLY the obfuscator's public port in the firewall.
  3. Check it: sudo $0 verify
  4. Issue a client: sudo $0 add-client laptop <your-server-host>
EOF
}

cmd_add_client() {
	local name="$1" server_host="$2"
	[[ -n "$name" && -n "$server_host" ]] || die "usage: $0 add-client <name> <server-host>"
	require_root

	local client_private client_public server_public address
	if $DRY_RUN; then
		client_private="<generated>"
		client_public="<derived>"
		server_public="<server public key>"
		address="${WG_SUBNET}.2"
	else
		command -v wg >/dev/null || die "wireguard-tools is not installed"
		[[ -f "$WG_CONF" ]] || die "no server configured; run '$0 init' first"

		client_private="$(wg genkey)"
		client_public="$(printf '%s' "$client_private" | wg pubkey)"
		server_public="$(cat "${WG_DIR}/server.pub")"

		# Next free address: count existing peers and add two (the
		# server holds .1).
		local peers
		peers="$(grep -c '^\[Peer\]' "$WG_CONF" || true)"
		address="${WG_SUBNET}.$((peers + 2))"

		cat >> "$WG_CONF" <<EOF

[Peer]
# ${name}
PublicKey = ${client_public}
AllowedIPs = ${address}/32
EOF
		wg syncconf "$WG_INTERFACE" <(wg-quick strip "$WG_INTERFACE")
	fi

	# The obfuscator credential, which is separate from WireGuard's own
	# keys: one authorizes the tunnel, the other the VPN inside it.
	local obfs_psk="<generated by obfsctl>"
	if ! $DRY_RUN; then
		obfs_psk="$("$OBFSCTL" -file "$CLIENTS_FILE" add "$name" | grep '^psk:' | sed 's/^psk: "//; s/"$//')"
		[[ -n "$obfs_psk" ]] || die "obfsctl did not issue a credential"
		systemctl reload obfsserver 2>/dev/null || warn "could not reload obfsserver; do it by hand"
	fi

	cat <<EOF

=== ${name}: WireGuard config (save as ${name}-wg.conf) ===
$(client_wireguard_config "$client_private" "$server_public" "$address" "$server_host")

=== ${name}: obfsclient config (save as ${name}-obfs.yaml) ===
mode: "tls"
psk: "${obfs_psk}"
local_addr: "127.0.0.1:${WG_PORT}"
remote_tls_addr: "${server_host}:443"
server_name: "www.example.com"
pinned_cert_sha256: "<the pin printed by gencert on this server>"

Both files go to the client. Start obfsclient first, then bring the
WireGuard interface up — WireGuard's Endpoint points at the local
obfuscator, not at the server.
EOF
}

cmd_verify() {
	local problems=0

	if [[ ! -f "$WG_CONF" ]]; then
		warn "no ${WG_CONF}: nothing to verify"
		return 1
	fi

	log "checking that WireGuard is not exposed directly"
	if ss -lunp 2>/dev/null | grep -q ":${WG_PORT}\b"; then
		local bound
		bound="$(ss -lun 2>/dev/null | awk -v p=":${WG_PORT}" '$0 ~ p {print $4}')"
		case "$bound" in
			127.0.0.1:*|\[::1\]:*)
				echo "  OK: WireGuard is bound to loopback (${bound})" ;;
			*)
				echo "  PROBLEM: WireGuard is listening on ${bound}." >&2
				echo "    A censor can reach it directly, and the obfuscator is then" >&2
				echo "    protecting nothing while still appearing to work." >&2
				problems=$((problems + 1)) ;;
		esac
	else
		warn "WireGuard does not appear to be listening on ${WG_PORT}"
	fi

	log "checking the interface MTU"
	local mtu
	mtu="$(ip link show "$WG_INTERFACE" 2>/dev/null | sed -n 's/.*mtu \([0-9]*\).*/\1/p')"
	if [[ -z "$mtu" ]]; then
		warn "interface ${WG_INTERFACE} is not up"
	elif [[ "$mtu" -le "$WG_MTU" ]]; then
		echo "  OK: MTU is ${mtu}, within the ${WG_MTU} the obfuscator needs"
	else
		echo "  PROBLEM: MTU is ${mtu}, above ${WG_MTU}." >&2
		echo "    Full-size packets will fragment once wrapped, which costs" >&2
		echo "    throughput and is a traffic pattern in its own right." >&2
		problems=$((problems + 1))
	fi

	log "checking the DROP rule for outside traffic to the WireGuard port"
	if iptables -C INPUT -p udp --dport "$WG_PORT" ! -s 127.0.0.1 -j DROP 2>/dev/null; then
		echo "  OK: outside traffic to ${WG_PORT} is dropped"
	else
		warn "the DROP rule is missing; restart wg-quick@${WG_INTERFACE} to reinstate it"
	fi

	if [[ "$problems" -gt 0 ]]; then
		echo >&2
		die "${problems} problem(s) found"
	fi
	log "all checks passed"
}

main() {
	local args=()
	for arg in "$@"; do
		case "$arg" in
			--dry-run) DRY_RUN=true ;;
			*) args+=("$arg") ;;
		esac
	done
	set -- "${args[@]:-}"

	case "${1:-}" in
		init)       cmd_init ;;
		add-client) cmd_add_client "${2:-}" "${3:-}" ;;
		verify)     cmd_verify ;;
		*)
			sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'
			exit 2 ;;
	esac
}

main "$@"
